framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:            
            async_priority_high: 'sync://'
            async_priority_low: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\Import': async_priority_high
            'App\Message\Export': async_priority_low
